language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - npm test
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: always 
    on_failure: always 