language: node_js
branches:
  only:
    - master
node_js:
  - '10.10.0'
script:
  - npm test
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: always 
    on_failure: always 